### ISSUE TITLE
Pequena correção gramatical

### ISSUE THREAD

**Issue by bruno-trivellato** [marciomr/apostila-seginf#1]
Na página 7 "suas contribuião", acredito que o desejado era "suas contribuições".

Parabéns pelo trabalho professor! A apostila parece excelente e já está salva nas minhas referências :)

**Comment by marciomr** [comment]
Obrigado Bruno. Vou mexer na apostila antes do curso do semestre que vem e aproveito e corrijo esse errinho :-)
